CREATE DATABASE IF NOT EXISTS shb;
USE shb;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(255),
  roll_no VARCHAR(50),
  full_name VARCHAR(255),
  dob DATE,
  phone VARCHAR(50),
  role ENUM('USER','ADMIN') DEFAULT 'USER',
  status ENUM('ACTIVE','PENDING_APPROVAL','SUSPENDED') DEFAULT 'PENDING_APPROVAL',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (
  user_id BIGINT PRIMARY KEY,
  bio TEXT,
  address VARCHAR(512),
  rating_avg DECIMAL(3,2) DEFAULT 0,
  rating_count INT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE books (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT,
  title VARCHAR(512),
  author VARCHAR(255),
  isbn VARCHAR(64),
  original_price DECIMAL(10,2),
  quality ENUM('NEW-LIKE','VERY_GOOD','GOOD','FAIR','POOR'),
  category ENUM('BUY','EXCHANGE','DONATE') DEFAULT 'BUY',
  price DECIMAL(10,2),
  description TEXT,
  status ENUM('AVAILABLE','SOLD','REMOVED') DEFAULT 'AVAILABLE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE book_images (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  book_id BIGINT,
  url VARCHAR(1024),
  is_primary BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE wishlists (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT,
  book_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE carts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  cart_id BIGINT,
  book_id BIGINT,
  qty INT DEFAULT 1,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  buyer_id BIGINT,
  total_amount DECIMAL(10,2),
  status ENUM('CREATED','PAID','SHIPPED','COMPLETED','CANCELLED') DEFAULT 'CREATED',
  payment_provider VARCHAR(255),
  payment_reference VARCHAR(255),
  receipt_url VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE order_items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT,
  book_id BIGINT,
  seller_id BIGINT,
  price DECIMAL(10,2),
  qty INT DEFAULT 1,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE SET NULL
);

CREATE TABLE transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT,
  provider VARCHAR(255),
  provider_txn_id VARCHAR(255),
  amount DECIMAL(10,2),
  status ENUM('PENDING','SUCCESS','FAILED'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  book_id BIGINT,
  reviewer_id BIGINT,
  seller_id BIGINT,
  rating INT,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE chat_threads (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  book_id BIGINT,
  buyer_id BIGINT,
  seller_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  thread_id BIGINT,
  sender_id BIGINT,
  message TEXT,
  read_by_receiver BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thread_id) REFERENCES chat_threads(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT,
  type VARCHAR(100),
  payload JSON,
  read_flag BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_user_approvals (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT,
  admin_id BIGINT,
  approved BOOLEAN DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);